['1217.43774414', '79.2541503906', '1430.63354492', '1791.22924805', '1317.41333008', '105.743408203', '1963.40942383', '1728.42407227']
False
('went into julia', '1217.43774414 79.2541503906 1430.63354492 1791.22924805 1317.41333008 105.743408203 1963.40942383 1728.42407227')
---> Error in python /root/MyEMEWSProject/MEModel/CalibrationTest.py 1217.43774414 79.2541503906 1430.63354492 1791.22924805 1317.41333008 105.743408203 1963.40942383 1728.42407227 
